{
  "type": "service_account",
  "project_id": "diario-473903",
  "private_key_id": "384a107d2c79f603779dae59d12c761f1794b7b7",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANB[...]S/Qh7yxCdF/E+eAWvrM=\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit-visa@diario-473903.iam.gserviceaccount.com",
  "client_id": "117811357994146898752",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  // ... outros campos
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-visa%40diario-473903.iam.gserviceaccount.com",
}
